import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "maplibre-gl/dist/maplibre-gl.css";
import { NotificationProvider } from "./context/NotificationContext";
import GoogleSignInButton from "../../components/GoogleSignInButton";

// ⬅️ IMPORTA TU COMPONENTE
import VentanaPrueba from "../booking/agenda/components/EnvConfigModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BookingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NotificationProvider>
      {/* ⬇️ CONTENIDO */}
      <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div style={{ display: "flex", justifyContent: "flex-end", padding: 12 }}>
          {/* <GoogleSignInButton /> */}
        </div>
        {children}
      </div>

      {/* ⬇️ FLOTANTE GLOBAL EN TODAS LAS PÁGINAS DE BOOKING */}
      <VentanaPrueba />

      {/* ⬇️ CONTENIDO */}
      <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </div>

    </NotificationProvider>
  );
}
